name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ryuichiueda/ubuntu22.04-ros2:latest
      options: --user root  # Dockerの実行時にrootとして実行

    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          mkdir -p /github/workspace  # GitHub Actionsの標準ディレクトリを作成
          rsync -av ./ /github/workspace/src/mypkg/
          cd /github/workspace
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y
          bash -xv ./src/mypkg/test/test.bash /github/workspace  # GitHub標準の作業ディレクトリを使う
        env:
          GITHUB_WORKSPACE: /github/workspace  # 環境変数をセット
